meal_plans/urls.py
from django.urls import path

from meal_plans.views import (
    MealPlansListView,
    MealPlansDeleteView,
    MealPlansDetailView,
    MealPlansCreateView,
    MealPlansEditView,
)

urlpatterns = [
    path("", MealPlansListView.as_view(), name="meal_plans_list"),
    path(
        "create/",
        MealPlansCreateView.as_view(),
        name="meal_plans_create",
    ),
    path(
        "<int:pk>/",
        MealPlansDetailView.as_view(),
        name="meal_plans_detail",
    ),
    path(
        "<int:pk>/edit",
        MealPlansEditView.as_view(),
        name="meal_plans_edit",
    ),
    path(
        "<int:pk>/delete",
        MealPlansDeleteView.as_view(),
        name="meal_plans_delete",
    ),
]

scrumptious/urls.py
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.views.generic.base import RedirectView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("meal_plans/", include("meal_plans.urls")),
    path("accounts/login/", auth_views.LoginView.as_view(), name="logout"),
    path("recipes/", include("recipes.urls")),
    path("tags/", include("tags.urls")),
    path("accounts/login/", auth_views.LoginView.as_view(), name="login"),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("recipes_list")),
        name="home",
    ),
]

tags/urls.py
from django.urls import path

from tags.views import (
    TagListView,
    TagDeleteView,
    TagDetailView,
    TagCreateView,
    TagUpdateView,
)

urlpatterns = [
    path("", TagListView.as_view(), name="tags_list"),
    path("<int:pk>/", TagDetailView.as_view(), name="tag_detail"),
    path("<int:pk>/delete/", TagDeleteView.as_view(), name="tag_delete"),
    path("new/", TagCreateView.as_view(), name="tag_new"),
    path("<int:pk>/edit/", TagUpdateView.as_view(), name="tag_edit"),
]

meal_plans/models.py
from django.db import models
from django.conf import settings
from recipes.models import Recipe

USER_MODEL = settings.AUTH_USER_MODEL


class MealPlan(models.Model):
    name = models.CharField(max_length=120)
    date = models.DateField()
    owner = models.ForeignKey(USER_MODEL, on_delete=models.CASCADE)
    recipes = models.ManyToManyField(Recipe, related_name="recipes")

meal_plans/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView
from meal_plans.models import MealPlan
from django.contrib.auth.mixins import LoginRequiredMixin


class MealPlansListView(LoginRequiredMixin, ListView):
    model = MealPlan
    template_name = "meal_plans/list.html"
    paginate_by = 2
    # context_object_name = "Banana"

    def get_queryset(self):
        return MealPlan.objects.filter(owner=self.request.user)


class MealPlansDetailView(LoginRequiredMixin, DetailView):
    model = MealPlan
    template_name = "meal_plans/detail.html"

    def get_queryset(self):
        return MealPlan.objects.filter(owner=self.request.user)

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context["rating_form"] = RatingForm()
    #     return context


# class MealPlansCreateView(CreateView):
#     model = MealPlan
#     template_name = "meal_plans/new.html"
#     fields = ["name", "description", "image"]
#     success_url = reverse_lazy("meal_plans_list")


class MealPlansEditView(LoginRequiredMixin, UpdateView):
    model = MealPlan
    template_name = "meal_plans/edit.html"
    fields = ["name", "date", "recipes"]
    success_url = reverse_lazy("meal_plans_list")

    def get_queryset(self):
        return MealPlan.objects.filter(owner=self.request.user)

    def get_success_url(self) -> str:
        return reverse_lazy("meal_plans_detail", args=[self.object.id])


class MealPlansDeleteView(LoginRequiredMixin, DeleteView):
    model = MealPlan
    template_name = "meal_plans/delete.html"
    success_url = reverse_lazy("meal_plans_list")

    def get_queryset(self):
        return MealPlan.objects.filter(owner=self.request.user)


class MealPlansCreateView(LoginRequiredMixin, CreateView):
    model = MealPlan
    template_name = "meal_plans/new.html"
    fields = ["name", "date", "recipes"]
    success_url = reverse_lazy("meal_plans_list")

    def form_valid(self, form):
        plan = form.save(commit=False)
        plan.owner = self.request.user
        plan.save()
        form.save_m2m()
        return redirect("meal_plans_detail", pk=plan.id)

meal_plans/templates/meal_plans/delete.html
{% extends 'base.html' %}

{% block content %}
  <main>
    <div class="delete-form">
      <form method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete "{{mealplan.name}}"?</p>
        {{ form.as_p }}
        <div>
          <button class="button">Delete</button>
        </div>
      </form>
    </div>
  </main>
  {% endblock content %}

meal_plans/templates/meal_plans/detail.html
{% extends 'base.html' %}
{% load markdownify %}

{% block content %}

<main class="recipe-detail">
  <div>
    <a href="{% url 'meal_plans_edit' mealplan.id %}">Edit</a>
    <a href="{% url 'meal_plans_delete' mealplan.id %}">Delete</a>
  </div>
      <h1>{{mealplan.name}}</h1>
      <div>
        <p>
      {%for recipe in mealplan.recipes.all%}
      <a href="{% url 'recipe_detail' recipe.pk %}">{{ recipe.name }}</a>
      {% endfor %}
        </p>
      </div>
</main>
  {% comment %} <main class="recipe-detail">
    <div>
      <a href="{% url 'meal_plans_edit' mealplan.id %}">Edit</a>
      <a href="{% url 'meal_plans_delete' mealplan.id %}">Delete</a>
    </div>
    {% if recipe.image %}
      <img src="{{ recipe.image }}" class="pull-right">
    {% endif %}
    <h1>{{ recipe.name }}</h1>
    <h2>by: {{ recipe.author | default_if_none:"Unknown" }}</h2>
    <p>
      Created on {{ recipe.created }} |
      Updated on {{ recipe.updated }}
    </p>
    <form method="post" action="{% url 'recipe_rating' mealplan.id %}">
      {% csrf_token %}
      <div class="rating-form-grid">
        {{ rating_form.as_p }}
        <button class="button">Rate</button>
      </div>
    </form>
    <p>Tags: {% for tag in recipe.tags.all %}{{ tag.word }} {% endfor %}</p>
    {{ recipe.description | markdownify }}
    <h2>Ingredients</h2>
    <table>
      <thead>
        <tr>
          <th colspan="2">Amount</th>
          <th>Food item</th>
        </tr>
      </thead>
      <tbody>
        {% for ingredient in recipe.ingredients.all %}
          <tr>
            <td>{{ ingredient.amount }}</td>
            <td>{{ ingredient.measure.name }}</td>
            <td>{{ ingredient.food.name }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    <h2>Steps</h2>
    <ol>
      {% for step in recipe.steps.all %}
        <li>{{ step.directions }}</li>
      {% endfor %}
    </ol>
  </main> {% endcomment %}
  {% endblock content %}

meal_plans/templates/meal_plans/edit.html
{% extends 'base.html' %}

{% block content %}
  <main class="recipe-form">
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <div class="control">
        <button class="button">Update</button>
      </div>
    </form>
  </main>
  {% endblock content %}

meal_plans/templates/meal_plans/list.html
{% extends 'base.html' %}
{% block pagination %}
  <div class="pagination">
    <span class="step-links">
      {% if page_obj.has_previous %}
        <a href="?page=1">&laquo; first</a>
        <a href="?page={{ page_obj.previous_page_number }}">previous</a>
      {% endif %}

      <span class="current">
        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
      </span>

      {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">next</a>
        <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
      {% endif %}
    </span>
  </div>
{% endblock pagination %}
{% block content %}

<div>
  <a href="/meal_plans/create/">Create a Meal Plan</a>
</div>

  <main class="recipe-grid">
    {% for meal_plans in mealplan_list %}
      <div class="recipe-card">

        <h2 class="recipe-card-title">
          <a href="{% url 'meal_plans_detail' meal_plans.pk %}">{{ meal_plans.name }}</a>
        </h2>
        <p class="recipe-card-date">{{ meal_plans.updated }}</p>

        {%for recipe in meal_plans.recipes.all%}
        <a href="{% url 'recipe_detail' recipe.pk %}">{{ recipe.name }}</a>
        {% endfor %}

      </div>
    {% endfor %}
  </main>

  {% endblock content %}

meal_plans/templates/meal_plans/new.html
{% extends 'base.html' %}

{% block content %}
  <main class="recipe-form">
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <div class="control">
        <button class="button">Create</button>
      </div>
    </form>
  </main>
{% endblock content %}